env:
  browser: true
  es6: true
  commonjs: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  'no-var': 'error'
  'brace-style': 'error'
  'import/prefer-default-export': 'off'
  'react/prop-types': 0
